version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
            - "./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    boxbilling:
        build: ./boxbilling
        image: boxbilling:v1
        ports:
            - "8004:80"
    php:
        image: bitnami/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
    composer:
        image: "composer"
        volumes:
            - "./web:/app"
        command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db: